const spec=(icon,label,value)=>({icon,label,value});

export const fighters=[
  {id:'volt',name:'VOLT',color:'#ff3d2e',accent:'#ffb3a9',speed:1.08,power:1.086,mass:.95,behaviors:['wallCharge'],ability:'LIVE WIRE',desc:'A reckless ricochet duelist. Every wall becomes a battery, and the next connection cashes stored momentum out as a stunning discharge.',specs:[spec('bolt','Charge capacity','5 wall hits'),spec('damage','Damage per charge','1.3 HP'),spec('gauge','Speed per wall','+2.5%')]},
  {id:'brick',name:'BRICK',color:'#3759ff',accent:'#aebaff',speed:.83,power:.8518,mass:1.18,behaviors:['armor'],ability:'BREAKWATER',desc:'A walking fortress with three visible armor plates. Focused pressure cracks the shell and opens a brief window before it rebuilds.',specs:[spec('shield','Plated reduction','26%'),spec('stack','Armor plates','3'),spec('clock','Rebuild time','3 seconds')]},
  {id:'mint',name:'MINT',color:'#20c997',accent:'#abf1dd',speed:1.12,power:1.0045,mass:.9,behaviors:['regeneration'],ability:'SECOND WIND',desc:'A slippery reset specialist. Mint wants space: surviving untouched long enough activates a rapid recovery state that contact immediately cancels.',specs:[spec('clock','Recovery delay','2 seconds'),spec('plus','Active healing','4.2 HP/s'),spec('impact','Hit response','Resets timer')]},
  {id:'goldie',name:'GOLDIE',color:'#f6b817',accent:'#ffe49b',speed:.96,power:.9447,mass:1.05,behaviors:['compoundPower'],ability:'JACKPOT',desc:'A combo investor whose returns compound across consecutive hits. Five coins light up before the whole stack cashes out in one premium strike.',specs:[spec('trend','Power per stack','+5%'),spec('stack','Cashout','After 5 hits'),spec('damage','Jackpot bonus','12 HP')]},
  {id:'void',name:'VOID',color:'#191919',accent:'#a4a4a4',speed:1.02,power:.8929,mass:1,behaviors:['siphon'],ability:'THE HUNGER',desc:'A predatory drain-tank that grows more dangerous near death. Hurt Void badly and every successful bite starts pulling it back from the brink.',specs:[spec('drop','Normal siphon','18%'),spec('heart','Below 50 HP','36% siphon'),spec('plus','Healing cap','100 HP')]},
  {id:'bubble',name:'BUBBLE',color:'#ef6dca',accent:'#ffc4ef',speed:1.16,power:.9377,mass:.86,behaviors:['bubbleShield'],ability:'POP SCREEN',desc:'A fragile escape artist wrapped in a renewable shell. The shield blanks one hit and violently rejects the attacker, then needs breathing room to reform.',specs:[spec('shield','Shield block','100%'),spec('launch','Pop recoil','135% reversal'),spec('clock','Recharge','4 seconds')]},
  {id:'moss',name:'MOSS',color:'#658c3a',accent:'#c2dd9e',speed:.88,power:.958,mass:1.12,behaviors:['thorns'],ability:'BRAMBLEHEART',desc:'A spiteful counter-tank that makes aggression costly. Reflected pain feeds its thorns until a full bloom roots the opponent in place.',specs:[spec('thorns','Damage returned','30%'),spec('gauge','Root threshold','18 damage'),spec('clock','Root duration','0.5 seconds')]},
  {id:'glitch',name:'GLITCH',color:'#9c52ff',accent:'#d9bcff',speed:1.05,power:1.0886,mass:.96,behaviors:['blink'],ability:'BACKDOOR',desc:'A tempo-breaking assassin that periodically teleports behind its target. Landing a hit before the phase window closes converts the ambush into bonus damage.',specs:[spec('shuffle','Blink interval','3.5 seconds'),spec('clock','Ambush window','1 second'),spec('damage','Ambush bonus','12 HP')]},
  {id:'frost',name:'FROST',color:'#7bdff2',accent:'#d8f7ff',speed:.91,power:1.0896,mass:1.04,behaviors:['coldSnap'],ability:'SHATTERPOINT',desc:'A setup-and-payoff controller. Heavy hits freeze the target; connecting again before the ice melts breaks it early for a brutal shatter.',specs:[spec('snow','Freeze duration','1.5 seconds'),spec('impact','Freeze trigger','Force above 8'),spec('damage','Shatter bonus','16 HP')]},
  {id:'ember',name:'EMBER',color:'#ff6b1a',accent:'#ffc49c',speed:1.01,power:.9617,mass:.97,behaviors:['afterburn'],ability:'FLASHPOINT',desc:'A relentless ignition fighter. Hits build burning stacks; striking a fully kindled opponent consumes the fire in an immediate explosion.',specs:[spec('flame','Maximum burn','2 stacks'),spec('clock','Burn duration','2 seconds'),spec('damage','Ignite bonus','10 HP')]},
  {id:'echo',name:'ECHO',color:'#00a6a6',accent:'#9ce3df',speed:1.04,power:.8348,mass:.94,behaviors:['echo'],ability:'AFTERIMAGE',desc:'A delayed-damage duelist whose every impact returns twice. Opponents can win the exchange and still fall to the second reverberation moments later.',specs:[spec('echo','First echo','35% at 0.23s'),spec('echo','Second echo','30% at 0.53s'),spec('damage','Total repeat','65%')]},
  {id:'rook',name:'ROOK',color:'#c9c3b9',accent:'#ffffff',speed:.82,power:.7824,mass:1.2,behaviors:['thirdHitBlock'],ability:'CASTLE WALL',desc:'A methodical counter-defender. Two hits test the gates; the third is completely parried and throws the aggressor back off rhythm.',specs:[spec('shield','Parry cadence','Every 3rd hit'),spec('block','Blocked damage','100%'),spec('clock','Counter stun','0.17 seconds')]},
  {id:'comet',name:'COMET',color:'#ff477e',accent:'#ffc2d4',speed:1.2,power:1.0886,mass:.82,behaviors:['continuousAcceleration'],ability:'TERMINAL VELOCITY',desc:'A glass-cannon projectile that grows deadlier in open space. Speed becomes bonus impact damage, but every successful ram burns away momentum.',specs:[spec('wind','Acceleration','6.2%/s'),spec('damage','Velocity bonus','Up to 12 HP'),spec('impact','Speed after hit','86%')]},
  {id:'static',name:'STATIC',color:'#e5ff00',accent:'#ffffff',speed:1,power:.9778,mass:.95,behaviors:['fourthStrike'],ability:'OVERLOAD',desc:'A rhythmic brawler with an obvious countdown. Three sparks warn the opponent before the fourth strike detonates and briefly locks them up.',specs:[spec('zap','Discharge','Every 4th hit'),spec('damage','Bonus damage','13 HP'),spec('clock','Overload stun','0.3 seconds')]},
  {id:'anchor',name:'ANCHOR',color:'#536878',accent:'#b9c8d2',speed:.72,power:.8482,mass:1.34,behaviors:['woundedPower'],ability:'LAST STAND',desc:'A slow raid boss that gets heavier and hits harder as its health disappears. Finishing Anchor means surviving its most dangerous form.',specs:[spec('anchor','Maximum power','+111%'),spec('weight','Maximum mass','+80%'),spec('heart','Scaling source','Missing health')]},
  {id:'orbit',name:'ORBIT',color:'#6c4cff',accent:'#c9bdff',speed:.96,power:.9684,mass:.98,behaviors:['orbitalSatellites'],ability:'TWIN MOONS',desc:'A moving area-control puzzle. Two physical satellites sweep around Orbit, clipping anyone who approaches on the wrong beat.',specs:[spec('orbit','Satellites','2'),spec('damage','Contact damage','5 HP'),spec('clock','Hit cooldown','0.4 seconds')]},
  {id:'saber',name:'SABER',color:'#d93636',accent:'#ffb0a8',speed:.92,power:.8655,mass:1.02,behaviors:['bladeTempo'],weapon:{type:'sword',length:88,width:14,angularSpeed:2.7,damage:21,cooldown:22,knockback:35,reversesOnContact:true},ability:'BLADEDANCE',desc:'A precision executioner whose body barely hurts, but a correctly aligned blade removes a huge chunk of health. The sword physically reverses off fighters and terrain, accelerating after every clean cut.',specs:[spec('sword','Neutral blade hit','18.2 HP'),spec('damage','Body damage','22% normal'),spec('rotate','Contact response','Reverse rotation'),spec('trend','Tempo per cut','+9% rotation')]},
  {id:'slugger',name:'SLUGGER',color:'#c47b38',accent:'#f1c590',speed:.88,power:.9283,mass:1.08,behaviors:['slugger'],weapon:{type:'bat',length:80,width:20,angularSpeed:-5.4,damage:4.5,cooldown:25,knockback:245,minimumLaunchSpeed:850,speedMultiplier:1.12},ability:'WALK-OFF',desc:'A positional power hitter. The fast-spinning bat redirects opponents along the path of its swing, setting up devastating bonus damage when the launch reaches an arena wall. Repeat hits keep accelerating the target.',specs:[spec('rotate','Swing rate','2× Saber'),spec('bat','Neutral bat hit','3.3 HP'),spec('launch','Minimum launch','850 px/s'),spec('trend','Repeat-hit speed','112%'),spec('damage','Wall-slam bonus','12 HP')]},
  {id:'shotgun',name:'SHOTGUN',color:'#e87924',accent:'#ffd09c',speed:.9,power:1,mass:1.06,behaviors:[],weapon:{type:'shotgun',projectile:true,length:66,width:22,angularSpeed:1.8,fireInterval:72,projectiles:5,spread:.48,projectileSpeed:1080,projectileDamage:4,projectileForce:7,projectileRadius:5,projectileLife:70,fireLabel:'BLAM!'},ability:'FIVE-CARD SPREAD',desc:'A close-range gambler with a rotating scattergun. Five pellets fan out at once, but each disappears on the first wall, hazard, or fighter it touches.',specs:[spec('damage','Neutral pellet','5.8 HP'),spec('stack','Pellets per blast','5'),spec('clock','Fire interval','1.2 seconds'),spec('gauge','Spread cone','27.5°')]},
  {id:'sniper',name:'SNIPER',color:'#496a81',accent:'#c8e1ed',speed:.78,power:1,mass:1.02,behaviors:[],weapon:{type:'sniper',projectile:true,length:94,width:13,angularSpeed:.82,fireInterval:156,projectiles:1,spread:0,projectileSpeed:1680,projectileDamage:34,projectileForce:16,projectileRadius:3,projectileLife:55,fireLabel:'CRACKSHOT!'},ability:'ONE SHOT, ONE KILL',desc:'A patient long-range executioner. Its narrow barrel rotates slowly and fires one devastating round that vanishes if any piece of terrain intercepts it.',specs:[spec('damage','Neutral round','79.4 HP'),spec('clock','Fire interval','2.6 seconds'),spec('ruler','Projectile width','6 px'),spec('wind','Muzzle speed','1,680 px/s')]},
];

// Balance coefficients are kept separate from kit identity so mechanical tuning
// never obscures the readable fantasy definitions above.
const powerTuning={volt:.8949,brick:.7413,mint:.9884,goldie:1.2155,void:.8148,bubble:1.2222,moss:.935,glitch:1.0686,frost:.915,ember:.9016,echo:.8682,rook:.6411,comet:1.5696,static:1.0352,anchor:.8615,orbit:1.1688,saber:.768,slugger:.7346,shotgun:1.448,sniper:2.3342};
const bodyDamageTuning={volt:.7,brick:.95,mint:.75,goldie:.55,void:.8,bubble:.5,moss:.65,glitch:.6,frost:.55,ember:.65,echo:.6,rook:.8,comet:.5,static:.6,anchor:.65,orbit:.45,saber:.22,slugger:.35,shotgun:.35,sniper:.25};
for(const fighter of fighters){
  fighter.power=powerTuning[fighter.id];fighter.bodyDamageScale=bodyDamageTuning[fighter.id];
  if(!fighter.specs.some(item=>item.label==='Body damage'))fighter.specs.push(spec('damage','Body damage',`${Math.round(fighter.bodyDamageScale*100)}% normal`));
}

export function getFighter(id){return fighters.find(fighter=>fighter.id===id);}
