import type { Fighter, FighterSpec, Material } from './types';
import {BURN_DAMAGE_PER_SECOND_PER_STACK} from './damage.js';

const spec=(icon:string,label:string,value:string):FighterSpec=>({icon,label,value});
const displayNumber=(value:number):string=>Number(value.toFixed(1)).toString();

export const fighters:Fighter[]=[
  {id:'volt',name:'VOLT',color:'#ff3d2e',accent:'#ffb3a9',speed:1.08,power:1.086,mass:.95,poisonDamageScale:1.2,behaviors:['wallCharge'],ability:'LIVE WIRE',desc:'A reckless ricochet duelist. Each wall bounce builds a Wall Charge, increasing speed. The next hit consumes every charge in a stunning Discharge that partially penetrates Parry.',specs:[spec('bolt','Wall Charge limit','5 charges'),spec('trend','Speed per Wall Charge','+2.5%'),spec('damage','Discharge damage','1.3 HP per charge'),spec('clock','Discharge stun','0.05 seconds per charge'),spec('shield','Discharge Parry penetration','25%'),spec('damage','Discharge vs. Comet bonus damage','+1 HP'),spec('drop','Poison vulnerability','+20% damage')]},
  {id:'brick',name:'BRICK',color:'#3759ff',accent:'#aebaff',speed:.83,power:.8518,mass:1.18,poisonDamageScale:.95,behaviors:['armor'],ability:'BREAKWATER',desc:'A walking fortress with three visible Armor Plates. Focused pressure causes Armor Break and opens a brief window before Armor Rebuild restores the shell. Armor Plates are especially effective against projectiles, Echoes, and Overload.',specs:[spec('stack','Armor Plate count','3 plates'),spec('shield','Armor Plate damage reduction','26%'),spec('shield','Projectile damage reduction','32%'),spec('clock','Armor Rebuild delay','3 seconds'),spec('shield','Poison damage reduction','5%')]},
  {id:'mint',name:'MINT',color:'#20c997',accent:'#abf1dd',speed:1.12,power:1.0045,mass:.9,behaviors:['regeneration'],ability:'SECOND WIND',desc:'A slippery reset specialist. Avoiding damage activates Second Wind; taking another hit immediately stops the healing and restarts its delay.',specs:[spec('clock','Second Wind trigger','2 seconds without damage'),spec('plus','Second Wind healing','4.2 HP/s')]},
  {id:'goldie',name:'GOLDIE',color:'#f6b817',accent:'#ffe49b',speed:.96,power:.9447,mass:1.05,behaviors:['compoundPower'],ability:'JACKPOT',desc:'A combo investor that gains a Coin after each hit. Coins compound Goldie’s damage until the fifth triggers Jackpot and cashes out the whole stack.',specs:[spec('trend','Damage per Coin','+5%'),spec('stack','Jackpot trigger','5 Coins'),spec('damage','Jackpot bonus damage','+12 HP')]},
  {id:'void',name:'VOID',color:'#191919',accent:'#a4a4a4',speed:1.02,power:.8929,mass:1,behaviors:['siphon'],ability:'THE HUNGER',desc:'A predatory drain-tank whose Siphon heals from damage dealt. Below half health, Feast doubles that healing and starts pulling Void back from the brink.',specs:[spec('drop','Siphon healing','18% of damage dealt'),spec('heart','Feast trigger','Below 50 HP'),spec('plus','Feast healing','36% of damage dealt')]},
  {id:'bubble',name:'BUBBLE',color:'#ef6dca',accent:'#ffc4ef',speed:1.16,power:.9377,mass:.86,behaviors:['bubbleShield'],ability:'POP SCREEN',desc:'A fragile escape artist wrapped in a renewable shield. Shield Pop completely blanks one hit and violently rejects the attacker, then must recharge.',specs:[spec('shield','Shield Pop damage block','100%'),spec('launch','Shield Pop recoil','135% of incoming speed'),spec('clock','Shield Pop recharge','4 seconds')]},
  {id:'moss',name:'MOSS',color:'#658c3a',accent:'#c2dd9e',speed:.88,power:.958,mass:1.12,poisonDamageScale:.68,behaviors:['thorns'],ability:'BRAMBLEHEART',desc:'A spiteful counter-tank whose Thorns return damage and charge Bramble Root on direct hits. Heavy attackers resist a small portion of the return. Once full, Bramble Root pins the attacker in place.',specs:[spec('thorns','Thorns damage','28.5–30% of damage taken'),spec('gauge','Bramble Root trigger','18 HP taken'),spec('clock','Bramble Root duration','0.5 seconds'),spec('heart','Healing received','−25%'),spec('shield','Poison damage reduction','32%')]},
  {id:'glitch',name:'GLITCH',color:'#9c52ff',accent:'#d9bcff',speed:1.05,power:1.0886,mass:.96,behaviors:['blink'],ability:'BACKDOOR',desc:'A tempo-breaking assassin. Backdoor periodically teleports Glitch behind its target; landing a hit during the brief opening triggers a bonus-damage Desync.',specs:[spec('shuffle','Backdoor interval','3.5 seconds'),spec('clock','Desync window','1 second'),spec('damage','Desync bonus damage','+12 HP')]},
  {id:'frost',name:'FROST',color:'#7bdff2',accent:'#d8f7ff',speed:.91,power:1.0896,mass:1.04,behaviors:['coldSnap'],ability:'SHATTERPOINT',desc:'A setup-and-payoff controller. A heavy direct hit triggers Freeze; connecting again before it ends triggers Ice Shatter for brutal bonus damage.',specs:[spec('impact','Freeze trigger','Heavy direct hit'),spec('snow','Freeze duration','1.5 seconds'),spec('damage','Ice Shatter bonus damage','+16 HP')]},
  {id:'ember',name:'EMBER',color:'#ff6b1a',accent:'#ffc49c',speed:1.01,power:.9617,mass:.97,behaviors:['afterburn'],ability:'FLASHPOINT',desc:'A relentless ignition fighter. Each hit adds a Burn stack; striking at the stack limit consumes the flames and triggers an immediate Ignite explosion.',specs:[spec('stack','Burn gained','1 per hit'),spec('flame','Burn limit','2 stacks'),spec('damage','Burn damage',`${BURN_DAMAGE_PER_SECOND_PER_STACK} HP/s per stack`),spec('clock','Burn duration','2 seconds'),spec('damage','Ignite bonus damage','+10 HP')]},
  {id:'echo',name:'ECHO',color:'#00a6a6',accent:'#9ce3df',speed:1.04,power:.8348,mass:.94,behaviors:['echo'],ability:'AFTERIMAGE',desc:'A delayed-damage duelist. Every damaging hit triggers Reverb, scheduling a First Echo and Second Echo that can finish the opponent moments later.',specs:[spec('damage','First Echo damage','35% of triggering damage'),spec('clock','First Echo delay','0.23 seconds'),spec('damage','Second Echo damage','30% of triggering damage'),spec('clock','Second Echo delay','0.53 seconds')]},
  {id:'rook',name:'ROOK',color:'#c9c3b9',accent:'#ffffff',speed:.82,power:.7824,mass:1.2,poisonDamageScale:.85,behaviors:['thirdHitBlock'],ability:'CASTLE WALL',desc:'A methodical counter-defender. Two hits test the gates; the third triggers Parry, completely blocking ordinary damage and briefly stunning the aggressor. Some abilities can partially penetrate Parry.',specs:[spec('shield','Parry trigger','Every 3rd hit'),spec('block','Parry damage block','100%'),spec('clock','Parry stun','0.17 seconds'),spec('shield','Poison damage reduction','15%')]},
  {id:'comet',name:'COMET',color:'#ff477e',accent:'#ffc2d4',speed:1.2,power:1.0886,mass:.82,behaviors:['continuousAcceleration'],ability:'TERMINAL VELOCITY',desc:'A glass-cannon projectile that accelerates while it has room to fly. Speed becomes bonus impact damage; at high speed, a ram breaks every Armor Plate. Each successful ram burns away some momentum.',specs:[spec('trend','Speed gain','~6% per second'),spec('damage','High-speed bonus damage','Up to +12 HP'),spec('impact','Speed after hit','86% retained')]},
  {id:'static',name:'STATIC',color:'#e5ff00',accent:'#ffffff',speed:1,power:.9778,mass:.95,behaviors:['fourthStrike'],ability:'OVERLOAD',desc:'A rhythmic brawler with an obvious countdown. Three sparks warn the opponent before the fourth hit triggers Overload and briefly locks them up.',specs:[spec('zap','Overload trigger','Every 4th hit'),spec('damage','Overload bonus damage','+13 HP'),spec('clock','Overload stun','0.3 seconds')]},
  {id:'anchor',name:'ANCHOR',color:'#536878',accent:'#b9c8d2',speed:.72,power:.8482,mass:1.34,behaviors:['woundedPower'],ability:'LAST STAND',desc:'A slow raid boss. Last Stand steadily increases Anchor’s damage and mass as health disappears, making its final moments the most dangerous.',specs:[spec('damage','Near-zero HP damage','+111%'),spec('weight','Near-zero HP mass','+80%')]},
  {id:'orbit',name:'ORBIT',color:'#6c4cff',accent:'#c9bdff',speed:.96,power:.9684,mass:.98,behaviors:['orbitalSatellites'],ability:'TWIN MOONS',desc:'A moving area-control puzzle. Two physical Satellites sweep around Orbit, clipping anyone who approaches on the wrong beat.',specs:[spec('orbit','Satellite count','2 satellites'),spec('rotate','Satellite spin','1.6 seconds/spin'),spec('damage','Satellite Hit damage','5 HP'),spec('clock','Satellite Hit cooldown','0.4 seconds')]},
  {id:'saber',name:'SABER',color:'#d93636',accent:'#ffb0a8',speed:.92,power:.8655,mass:1.02,behaviors:['bladeTempo'],weapon:{type:'sword',length:88,width:14,angularSpeed:2.7,damage:21,cooldown:22,knockback:35,reversesOnContact:true},ability:'BLADEDANCE',desc:'A precision executioner whose body barely hurts. A clean Blade Hit deals critical damage and triggers Riposte, reversing the blade and making it spin faster. The blade also reverses when it strikes terrain.',specs:[spec('sword','Blade Hit damage','16.1 HP'),spec('damage','Body Hit damage','22% of standard'),spec('rotate','Starting blade spin','2.3 seconds/spin'),spec('trend','Spin speed per Riposte','+9%')]},
  {id:'slugger',name:'SLUGGER',color:'#c47b38',accent:'#f1c590',speed:.88,power:.9283,mass:1.08,behaviors:['slugger'],weapon:{type:'bat',length:80,width:20,angularSpeed:-5.4,damage:4.5,cooldown:25,knockback:245,minimumLaunchSpeed:850,speedMultiplier:1.12},ability:'WALK-OFF',desc:'A positional power hitter. Bat Hit redirects and accelerates the opponent along the bat’s swing, arming bonus damage if the launch becomes a Wall Slam. Repeated Bat Hits can keep building speed.',specs:[spec('bat','Bat Hit damage','3.1 HP'),spec('rotate','Bat spin','1.2 seconds/spin'),spec('trend','Speed per Bat Hit','At least +12%'),spec('damage','Wall Slam damage','12 HP')]},
  {id:'shotgun',name:'SHOTGUN',color:'#e87924',accent:'#ffd09c',speed:.9,power:1,mass:1.06,behaviors:[],weapon:{type:'shotgun',projectile:true,length:66,width:22,angularSpeed:1.8,fireInterval:72,projectiles:5,spread:.48,projectileSpeed:1080,projectileDamage:4,projectileForce:7,projectileRadius:5,projectileLife:70,fireLabel:'BLAM!'},ability:'FIVE-CARD SPREAD',desc:'A close-range gambler with a rotating scattergun. Each Blast fires five Pellets in a cone; a Pellet disappears when it first touches terrain, a hazard, or a fighter.',specs:[spec('damage','Pellet damage','5.1 HP'),spec('projectile','Pellet count','5 projectiles'),spec('gauge','Blast spread','27.5° cone'),spec('clock','Blast interval','1.2 seconds'),spec('rotate','Barrel spin','3.5 seconds/spin')]},
  {id:'sniper',name:'SNIPER',color:'#496a81',accent:'#c8e1ed',speed:.78,power:1,mass:1.02,behaviors:[],weapon:{type:'sniper',projectile:true,length:94,width:13,angularSpeed:.82,fireInterval:156,projectiles:1,spread:0,projectileSpeed:1680,projectileDamage:34,projectileForce:16,projectileRadius:3,projectileLife:55,fireLabel:'CRACKSHOT!'},ability:'ONE SHOT, ONE KILL',desc:'A patient long-range executioner. Its narrow barrel rotates slowly and fires one devastating Round that vanishes if terrain or a hazard intercepts it.',specs:[spec('damage','Round damage','54.5 HP'),spec('clock','Round interval','2.6 seconds'),spec('rotate','Barrel spin','7.7 seconds/spin')]},
  {id:'lance',name:'LANCE',color:'#feed9a',accent:'#fff8d4',speed:.86,power:1,mass:1.06,behaviors:['joust'],weapon:{type:'lance',length:104,width:11,angularSpeed:1.35,damage:.8,cooldown:18,knockback:55,reversesOnContact:true},ability:'TILT AT FATE',desc:'A feast-or-famine cavalry charger. Lance barely scratches between Jousts, but each hit strengthens the next fast, invulnerable Joust. Brace softens reckless high-speed body hits.',specs:[spec('rotate','Lance spin','4.7 seconds/spin'),spec('clock','Joust interval','2.5 seconds'),spec('shield','Joust damage immunity','100%'),spec('damage','Base Joust bonus damage','+12.9 HP'),spec('trend','Joust damage per hit','+1.5 HP'),spec('gauge','Maximum Joust bonus damage','+27.9 HP'),spec('damage','Joust vs. heavy fighters','+20% damage'),spec('shield','Brace damage reduction','45%')]},
  {id:'grower',name:'GROWER',color:'#35c94a',accent:'#b8ff82',speed:.9,power:1,mass:.92,behaviors:['growth'],ability:'NO ROOM LEFT',desc:'A living space-control problem. Every wall bounce and Body Hit makes Grower physically larger, trading a tiny early footprint for relentless late-fight contact pressure—and becoming easier to hit in return.',specs:[spec('trend','Size per wall bounce','+2.3% of base size'),spec('impact','Size per Body Hit','+4.4% of base size'),spec('gauge','Maximum size','155% of base size')]},
  {id:'flail',name:'FLAIL',color:'#e2947c',accent:'#ffd5c9',speed:.86,power:1,mass:1.04,behaviors:['wildFlail'],ability:'LOOSE CANNON',desc:'A chaotic scaler built around a separate swinging Flail Head. Each difficult Flail Hit partially penetrates guards and makes the wandering head larger and more damaging.',specs:[spec('rotate','Flail spin','0.73 seconds/spin'),spec('damage','Base Flail Hit damage','8.5 HP'),spec('trend','Damage per Flail Hit','+1 HP'),spec('gauge','Maximum Flail Hit damage','26.8 HP'),spec('trend','Maximum Flail Head size','2× base size'),spec('shield','Flail Hit guard penetration','50%')]},
  {id:'polar',name:'POLAR',color:'#3366d6',accent:'#9beeff',speed:.96,power:1,mass:1,poisonDamageScale:1.3,behaviors:['polarityDrive'],ability:'FIELD REVERSAL',desc:'A rule-breaking position controller. Polar begins by attracting its opponent; every direct hit reverses the field between attraction and violent repulsion. The field cushions Comet rams, but draws projectiles and loose ability objects dangerously inward.',specs:[spec('shuffle','Field Reversal trigger','Each direct hit'),spec('shield','Comet damage reduction','10%'),spec('damage','Ability vulnerability','+10% damage'),spec('damage','Projectile vulnerability','+40% damage'),spec('drop','Poison vulnerability','+30% damage')]},
  {id:'mothership',name:'MOTHERSHIP',color:'#5b3c88',accent:'#c8ff65',speed:.8,power:1,mass:1.1,behaviors:['droneCarrier'],ability:'SCRAMBLE THE SWARM',desc:'A patient carrier that launches up to four homing Seekers. Fast fighters can juke their limited steering, but suffer a harder Seeker Hit if caught. A Seeker that pops a shield triggers Shield Jam and delays its return.',specs:[spec('clock','Seeker interval','1.53 seconds'),spec('stack','Active Seeker limit','4 Seekers'),spec('clock','Seeker arming time','0.3 seconds'),spec('damage','Seeker Hit damage','4.3–10.6 HP'),spec('damage','Seeker vs. shields','+80% damage'),spec('shield','Melee damage reduction','15%'),spec('clock','Shield Jam recharge','6 seconds')]},
  {id:'spider',name:'SPIDER',color:'#e2383f',secondaryColor:'#2758c7',accent:'#ffffff',speed:1.02,power:1,mass:.84,radiusScale:.67,behaviors:['webSlinger'],ability:'THWIPLINE',desc:'A tiny aerial trickster with three grapple outcomes. Grapple Swing accelerates Spider into a heavy Swing Strike. Striking geometry triggers Perch before a leap, while catching a fighter triggers Web Pull and whips the stopped target inward using its own momentum.',specs:[spec('clock','Grapple interval','0.9–1.8 seconds'),spec('clock','Grapple Swing duration','1.6 seconds'),spec('damage','Swing Strike bonus damage','+18–36 HP'),spec('clock','Perch duration','1 second'),spec('damage','Web Pull bonus damage','Up to +20 HP')]},
  {id:'claymore',name:'CLAYMORE',color:'#596b3d',accent:'#ffb14a',speed:.88,power:1,mass:1.08,behaviors:['ordnanceLayer','explosiveResistance'],ability:'DANGER CLOSE',desc:'A demolition tactician that leaves armed Mines in its wake. Mine Blast violently launches whoever finds one, although Claymore resists most of the damage. Grenades burst against fighters or terrain into twelve pieces of Shrapnel.',specs:[spec('clock','Mine interval','3.7–4.7 seconds'),spec('stack','Mine limit','5 active'),spec('damage','Mine Blast damage','34.2 HP'),spec('shield','Explosion damage reduction','65%'),spec('clock','Grenade interval','3.5–4.5 seconds'),spec('projectile','Shrapnel count','12 projectiles'),spec('damage','Shrapnel damage','3.8 HP each')]},
  {id:'cobra',name:'COBRA',color:'#2f8f46',accent:'#d7ff63',speed:1,power:1,mass:1.05,behaviors:['venom'],ability:'DEATH COIL',desc:'A patient attrition hunter whose body barely hurts on contact. Every Venom Hit adds another equal, permanent Poison stack, turning a long fight into an accelerating race against the clock. Poison attacks from within and ignores physical protection.',specs:[spec('stack','Poison gained','1 stack per Venom Hit'),spec('damage','Poison damage','1.24 HP/s per stack'),spec('clock','Poison duration','Permanent'),spec('shield','Poison armor bypass','100%'),spec('damage','Body Hit damage','12% of standard')]},
];

fighters.push(
  {id:'corsair',name:'CORSAIR',color:'#147d91',accent:'#ffd478',speed:1.04,power:1,mass:.94,behaviors:['crescentRaider'],ability:'RETURN TO SENDER',desc:'A swaggering raider with a returning crescent. Cast ricochets off terrain before Recall bends it back toward Corsair. The stronger Backslash can catch an opponent from behind; the blade must return before another Cast.',specs:[spec('damage','Cast damage','10 HP'),spec('clock','Recall delay','0.75 seconds'),spec('damage','Backslash damage','17 HP'),spec('shield','Backslash shield penetration','50%'),spec('clock','Cast recovery','1.42 seconds')]},
  {id:'dynamo',name:'DYNAMO',color:'#de5830',accent:'#ffe8aa',speed:.96,power:1,mass:1.04,behaviors:['rocketBoxer'],ability:'HEAVY DELIVERY',desc:'A headstrong rocket boxer with a repeating attack cycle. Wind Up tracks the opponent, then Dash commits Dynamo to a straight line. Contact lands Rocket Punch, which hits heavier fighters harder and partially penetrates shields; a missed Dash can trigger Ground Burst instead. Both outcomes end in Recovery. Impact Guard caps crushing Body Hits and melee hits, but Poison bypasses it.',specs:[spec('clock','Wind Up duration','0.5 seconds'),spec('damage','Rocket Punch bonus damage','+22–34 HP'),spec('shield','Rocket Punch shield penetration','50%'),spec('damage','Ground Burst damage','13 HP'),spec('clock','Recovery duration','0.5 seconds'),spec('shield','Body Hit damage cap','12 HP · 16 HP during Dash'),spec('shield','Melee damage cap','20 HP'),spec('damage','Weapon vulnerability','+30% damage'),spec('drop','Poison vulnerability','+50% damage')]},
  {id:'hourglass',name:'HOURGLASS',color:'#7965b5',accent:'#f5d184',speed:1.06,power:1,mass:.96,behaviors:['timeThief'],ability:'BORROWED TIME',desc:'A time thief that places a Bookmark while damage taken charges Time Break. When Rewind triggers, Hourglass returns to the Bookmark with reversed momentum and fires radial Time Shards from the position it left. The first Time Shard to connect triggers Time Break; terrain and hazards absorb the volley.',specs:[spec('clock','Bookmark duration','1.75 seconds'),spec('projectile','Time Shard count','12 projectiles'),spec('gauge','Time Break charge limit','55 HP taken'),spec('damage','Time Break damage','3–8.5 HP'),spec('clock','Rewind recovery','1.67 seconds')]},
);

fighters.push(
  {id:'phantom',name:'PHANTOM',color:'#4a3675',accent:'#9ff3ff',shineColor:'#c8c1dc',speed:1.05,power:1,mass:.92,behaviors:['phantomReplay'],ability:'SECOND SELF',desc:'A temporal duelist that periodically sheds an Afterimage to retrace its recent path. If the replay touches the opponent, it lands Echo Strike. While the Afterimage exists, the next incoming hit triggers Misdirect: Phantom takes reduced damage, swaps into the replay’s position, and dismisses it. Committed charge attacks are easier to evade than ordinary hits.',specs:[spec('clock','Afterimage interval','1.25–2 seconds'),spec('clock','Afterimage replay','1.45 seconds'),spec('damage','Echo Strike damage','13 HP'),spec('shield','Misdirect damage reduction','60%'),spec('shield','Misdirect charge reduction','80%')]},
  {id:'alchemist',name:'ALCHEMIST',color:'#6e4294',accent:'#b6ec52',shineColor:'#d9c9e3',speed:.93,power:1,mass:.98,behaviors:['fieldAlchemy'],ability:'VOLATILE THEORY',desc:'A terrain chemist that cycles through Acid Flask, Tonic Flask, and Catalyst Flask. Acid Pool burns the opponent while Tonic Pool heals either fighter. Catalyst reacts with nearby pools: Acid Reaction explodes for damage, while Tonic Reaction releases an instant healing burst.',specs:[spec('clock','Flask interval','1.25 seconds'),spec('clock','Pool duration','4 seconds'),spec('damage','Acid Pool damage','2.2 HP/s'),spec('plus','Tonic Pool healing','3 HP/s'),spec('damage','Acid Reaction damage','16 HP'),spec('plus','Tonic Reaction healing','12 HP'),spec('damage','Catalyst Burst damage','7 HP')]},
  {id:'ronin',name:'RONIN',color:'#26344f',accent:'#ff4c75',shineColor:'#b9c3d3',speed:.9,power:1,mass:1.02,poisonDamageScale:1.3,behaviors:['drawBlade'],ability:'ONE CLEAN LINE',desc:'A patient duelist that stops to enter Focus before committing to a straight-line Draw Cut. Taking a Body Hit during Focus triggers Counter, briefly staggering and chasing the attacker; faster attackers empower Counter Cut. Ronin reads predictable high-speed rams and committed charges even outside Focus, while cuts bite deeper into raid-boss-weight targets. Weapons, projectiles, and other abilities punish the exposed stance. Each successful cut leaves a forceful, controlled deflection instead of carrying dash momentum through the opponent. Successful cuts build Resolve, and the third becomes a stronger Final Cut that partially penetrates shields.',specs:[spec('clock','Focus duration','0.5 seconds'),spec('damage','Draw Cut bonus damage','+24 HP'),spec('shield','Counter damage reduction','80%'),spec('clock','Counter stagger','0.2 seconds'),spec('damage','Counter Cut bonus damage','+30 HP'),spec('damage','Counter Cut speed bonus','Up to +45 HP'),spec('damage','Heavy target cut bonus','+2 HP'),spec('shield','Charge damage reduction','45%'),spec('shield','High-speed ram reduction','35%'),spec('damage','Focus special vulnerability','+35% damage'),spec('drop','Poison vulnerability','+30% damage'),spec('stack','Final Cut trigger','3 successful cuts'),spec('damage','Final Cut bonus damage','+42 HP'),spec('shield','Final Cut shield penetration','50%'),spec('clock','Recovery duration','0.6 seconds')]},
);

fighters.push(
  {id:'gatekeeper',name:'GATEKEEPER',color:'#30256f',accent:'#54e7ff',shineColor:'#c6c3ee',speed:1.02,power:1,mass:.96,behaviors:['portalArchitect'],ability:'TWO-WAY STREET',desc:'A spatial trickster that links two Portals on different arena walls. Any fighter or projectile can enter; it preserves its speed but redirects along the exit wall. Gatekeeper’s own transfer briefly arms Crosscut. After enough total transfers, the Portal pair triggers Collapse and rebuilds elsewhere.',specs:[spec('clock','Portal interval','1.17–3 seconds'),spec('clock','Crosscut window','1.25 seconds'),spec('damage','Crosscut bonus damage','+8 HP'),spec('stack','Collapse trigger','6 transfers')]},
  {id:'conductor',name:'CONDUCTOR',color:'#174f5e',accent:'#ffe34f',shineColor:'#b8d9de',speed:.94,power:1,mass:1,behaviors:['circuitArchitect'],ability:'LIVE CIRCUIT',desc:'A battlefield engineer that installs a Pylon at each new wall impact. Two Pylons form a damaging Arc; three trigger Overcharge. An Arc interrupts an active charge, while any projectile crossing it becomes a Charged Projectile, regardless of who fired it. When Overcharge ends, Burnout removes the oldest Pylon and the network evolves.',specs:[spec('stack','Arc trigger','2 Pylons'),spec('damage','Arc damage','3 HP'),spec('clock','Arc hit cooldown','0.5 seconds'),spec('damage','Charge interrupt bonus damage','+5 HP'),spec('stack','Overcharge trigger','3 Pylons'),spec('clock','Overcharge duration','2 seconds'),spec('damage','Arc damage during Overcharge','5 HP'),spec('trend','Charged Projectile damage','+25%')]},
  {id:'matryoshka',name:'MATRYOSHKA',color:'#a83252',accent:'#ffd18a',shineColor:'#edb8c5',speed:.82,power:1,mass:1.15,radiusScale:1.15,behaviors:['nestedArsenal'],ability:'FINAL FORM',desc:'A three-stage arsenal hidden inside breakable shells. Outer Shell is large, armored, and carries a launching Hammer. Shell Break reveals a smaller, faster Twin Blade form. Core Exposed becomes tiny, accelerates continuously, and periodically spends its own HP to fire an explosive Meltdown volley.',specs:[spec('shield','Outer Shell damage reduction','28%'),spec('damage','Hammer Blow damage','14 HP'),spec('heart','Shell Break trigger','At 66 HP'),spec('damage','Twin Slash damage','7 HP'),spec('heart','Core Exposed trigger','At 33 HP'),spec('projectile','Meltdown Core Shards','16 projectiles'),spec('damage','Core Shard damage','6 HP each'),spec('damage','Meltdown self-damage','8 HP'),spec('clock','Meltdown interval','3–4 seconds')]},
);

fighters.push(
  {id:'stillpoint',name:'STILLPOINT',color:'#d8832f',accent:'#fff0a8',shineColor:'#f2c895',speed:.9,power:1,mass:1,behaviors:['stillMind'],ability:'EMPTY HAND',desc:'A serene martial master who stops once to Meditate behind a one-hit Serenity Ward. After the Ward breaks, up to two hits leave Stillpoint Disturbed and extend Meditate. Completing Meditate leaves Stillpoint Centered and readies one devastating Palm Strike that halts and launches its target.',specs:[spec('clock','Meditate duration','3 seconds'),spec('block','Serenity Ward damage block','100%'),spec('shield','Meditate damage reduction','25%'),spec('damage','Palm Strike bonus damage','+35 HP'),spec('shield','Palm Strike shield penetration','50%')]},
  {id:'ascendant',name:'ASCENDANT',color:'#665f67',accent:'#d8b7ff',shineColor:'#aaa4ab',speed:.82,power:1,mass:1.12,radiusScale:1.12,behaviors:['secondDawn'],ability:'ASCENSION',desc:'A stone guardian carrying one luminous second life. Its shell softens ordinary Body Hits, but weapons and special attacks strike at full strength. The first lethal blow begins Ascension: Ascendant stops, becomes invulnerable, and rejects incoming fighters while its shell explodes away. It emerges Ascended—a smaller, faster glass cannon with twice the damage and no third life.',specs:[spec('shield','Body Hit damage reduction','20%'),spec('heart','Ascension trigger','At 0 HP'),spec('clock','Ascension invulnerability','1.2 seconds'),spec('heart','Ascended health','35 HP'),spec('trend','Ascended damage','+100%')]},
  {id:'luchador',name:'LUCHADOR',color:'#22a6a1',secondaryColor:'#f04f45',accent:'#ffe260',shineColor:'#9ce3df',speed:1.02,power:1,mass:.98,behaviors:['ringShowman'],ability:'THE MAIN EVENT',desc:'A fearless showman who makes every fight The Main Event. An ordinary Body Hit becomes a Clinch that spins both fighters around the ring, then ends with a Ring Toss that hurls them in opposite directions. After Ring Toss, Luchador must recover before starting another Clinch.',specs:[spec('damage','Clinch bonus damage','+18 HP'),spec('shield','Clinch shield penetration','25%'),spec('clock','Clinch duration','0.4 seconds'),spec('clock','Ring Toss recovery','2 seconds')]},
);

fighters.push(
  {id:'neon',name:'NEON',color:'#ee3d9b',secondaryColor:'#342c78',accent:'#57f3ff',shineColor:'#f7b6db',speed:.96,power:1,mass:.96,behaviors:['spotlightSweep'],ability:'LIGHT SHOW',desc:'A dazzling arena idol who repeatedly turns the fight into a performance. Neon stops beneath a Spotlight and tracks the opponent during a visible Wind Up, then sweeps a laser across the arena. Catching the opponent in the beam lands one Encore before Neon begins preparing the next Light Show.',specs:[spec('clock','Wind Up duration','1 second'),spec('clock','Light Show duration','0.9 seconds'),spec('damage','Encore damage','10 HP'),spec('shield','Encore shield penetration','20%'),spec('clock','Light Show recovery','3 seconds')]},
  {id:'shogun',name:'SHOGUN',color:'#202b52',accent:'#ff4f9a',shineColor:'#aeb7d1',speed:1.04,power:1,mass:.92,behaviors:['dataBlade'],ability:'PHASE CUT',desc:'A cyber-ninja who throws a Data Blade until it becomes an arena-wall Anchor. After a brief warning, Shogun Blinks to the Anchor and charges through the opponent’s last position. Connecting during the charge lands Phase Cut; a miss still commits Shogun to the full dash.',specs:[spec('clock','Anchor warning','0.6 seconds'),spec('damage','Phase Cut bonus damage','+30 HP'),spec('shield','Phase Cut shield penetration','35%'),spec('clock','Phase Cut recovery','2.75 seconds')]},
  {id:'capo',name:'CAPO',color:'#322d35',accent:'#f0c45b',shineColor:'#aaa4ad',speed:.9,power:1,mass:1.04,behaviors:['loyalEnforcer'],ability:'LOYALTY PAYS',desc:'An unassuming boss shadowed by one orbiting Enforcer. While the Enforcer is ready, the next damaging hit triggers Intercept: it absorbs part of the blow, knocks the attacker away, and delivers Retaliation. Capo is exposed until the Enforcer returns.',specs:[spec('block','Intercept damage block','6 HP'),spec('damage','Retaliation damage','8 HP'),spec('clock','Enforcer recovery','4 seconds')]},
);

// Balance coefficients are kept separate from kit identity so mechanical tuning
// never obscures the readable fantasy definitions above.
const powerTuning:Record<string,number>={volt:.768,brick:.7,mint:.9083,goldie:1.0686,void:.7613,bubble:1.1287,moss:.8565,glitch:.9484,frost:.78,ember:.788,echo:.7947,rook:.601,comet:1.4159,static:.9283,anchor:.8014,orbit:1.0686,saber:.768,slugger:.6945,shotgun:1.2823,sniper:1.603,lance:1.15,grower:1.1488,flail:1.22,polar:1.32,mothership:.5,spider:.95,claymore:.9,cobra:1};
const bodyDamageTuning:Record<string,number>={volt:.7,brick:.95,mint:.75,goldie:.55,void:.8,bubble:.5,moss:.65,glitch:.6,frost:.55,ember:.65,echo:.6,rook:.8,comet:.5,static:.6,anchor:.65,orbit:.45,saber:.22,slugger:.35,shotgun:.35,sniper:.25,lance:.1,grower:.68,flail:.14,polar:.58,mothership:.625,spider:.62,claymore:.38,cobra:.12};
const bodyMaterials:Record<string,Material>={volt:'plastic',brick:'stone',mint:'rubber',goldie:'metal',void:'energy',bubble:'rubber',moss:'wood',glitch:'energy',frost:'glass',ember:'ceramic',echo:'glass',rook:'metal',comet:'glass',static:'energy',anchor:'metal',orbit:'metal',saber:'plastic',slugger:'plastic',shotgun:'plastic',sniper:'plastic',lance:'wood',grower:'rubber',flail:'metal',polar:'energy',mothership:'metal',spider:'rubber',claymore:'metal',cobra:'rubber'};
const weaponMaterials:Record<string,Material>={sword:'metal',bat:'wood',lance:'metal',shotgun:'metal',sniper:'metal'};
Object.assign(powerTuning,{corsair:1,dynamo:1.25,hourglass:1.64,gatekeeper:1.4211,conductor:.8273,matryoshka:.84});
Object.assign(powerTuning,{phantom:.96,alchemist:1.614,ronin:.98});
Object.assign(powerTuning,{stillpoint:.83,ascendant:.9,luchador:.75});
Object.assign(powerTuning,{neon:.92,shogun:.97,capo:.88});
Object.assign(bodyDamageTuning,{gatekeeper:.38,conductor:.42,matryoshka:.35,phantom:.42,alchemist:.38,ronin:.12});
Object.assign(bodyDamageTuning,{stillpoint:.6,ascendant:.4,luchador:.32});
Object.assign(bodyDamageTuning,{neon:.65,shogun:.34,capo:.52});
Object.assign(bodyMaterials,{gatekeeper:'energy',conductor:'metal',matryoshka:'wood',phantom:'energy',alchemist:'glass',ronin:'metal'});
Object.assign(bodyMaterials,{stillpoint:'wood',ascendant:'stone',luchador:'rubber'});
Object.assign(bodyMaterials,{neon:'energy',shogun:'metal',capo:'plastic'});
bodyDamageTuning.dynamo=.12;
fighters.find(f=>f.id==='dynamo')!.poisonDamageScale=1.5;
for(const fighter of fighters){
  const shineColors:Record<string,string>={corsair:'#b6dfe7',dynamo:'#ffc6b5',hourglass:'#d8cfee'};
  if(shineColors[fighter.id])fighter.shineColor=shineColors[fighter.id];
  if(fighter.id==='hourglass')fighter.accent=fighter.color;
  fighter.power=powerTuning[fighter.id]??1;fighter.bodyDamageScale=bodyDamageTuning[fighter.id]??.35;fighter.material=bodyMaterials[fighter.id]??'plastic';
  if(fighter.weapon)fighter.weapon.material=weaponMaterials[fighter.weapon.type]??'plastic';
  const damageSpecs:Record<string,Record<string,string>>={
    corsair:{'Cast damage':`${displayNumber(10*fighter.power)} HP`,'Backslash damage':`${displayNumber(17*fighter.power)} HP`},
    dynamo:{'Rocket Punch bonus damage':`+${displayNumber(22*fighter.power)}–${displayNumber(34*fighter.power)} HP`,'Ground Burst damage':`${displayNumber(13*fighter.power)} HP`},
    hourglass:{'Time Break damage':`${displayNumber(3*fighter.power)}–${displayNumber(8.5*fighter.power)} HP`},
    gatekeeper:{'Crosscut bonus damage':`+${displayNumber(8*fighter.power)} HP`},
    conductor:{'Arc damage':`${displayNumber(3*fighter.power)} HP`,'Charge interrupt bonus damage':`+${displayNumber(5*fighter.power)} HP`,'Arc damage during Overcharge':`${displayNumber(5*fighter.power)} HP`},
    matryoshka:{'Hammer Blow damage':`${displayNumber(14*fighter.power)} HP`,'Twin Slash damage':`${displayNumber(7*fighter.power)} HP`,'Core Shard damage':`${displayNumber(6*fighter.power)} HP each`},
    phantom:{'Echo Strike damage':`${displayNumber(13*fighter.power)} HP`},
    alchemist:{'Acid Pool damage':`${displayNumber(2.2*fighter.power)} HP/s`,'Acid Reaction damage':`${displayNumber(16*fighter.power)} HP`,'Catalyst Burst damage':`${displayNumber(7*fighter.power)} HP`},
    ronin:{'Draw Cut bonus damage':`+${displayNumber(24*fighter.power)} HP`,'Counter Cut bonus damage':`+${displayNumber(30*fighter.power)} HP`,'Counter Cut speed bonus':`Up to +${displayNumber(45*fighter.power)} HP`,'Heavy target cut bonus':`+${displayNumber(2*fighter.power)} HP`,'Final Cut bonus damage':`+${displayNumber(42*fighter.power)} HP`},
    stillpoint:{'Palm Strike bonus damage':'+35 HP'},
    luchador:{'Clinch bonus damage':`+${displayNumber(18*fighter.power)} HP`},
    neon:{'Encore damage':`${displayNumber(10*fighter.power)} HP`},
    shogun:{'Phase Cut bonus damage':`+${displayNumber(30*fighter.power)} HP`},
    capo:{'Retaliation damage':`${displayNumber(8*fighter.power)} HP`},
  };
  for(const item of fighter.specs){const value=damageSpecs[fighter.id]?.[item.label];if(value)item.value=value;}
}

export function getFighter(id:string):Fighter|undefined{return fighters.find(fighter=>fighter.id===id);}
