import type { Fighter, FighterSpec, Material } from './types';

const spec=(icon:string,label:string,value:string):FighterSpec=>({icon,label,value});

export const fighters:Fighter[]=[
  {id:'volt',name:'VOLT',color:'#ff3d2e',accent:'#ffb3a9',speed:1.08,power:1.086,mass:.95,behaviors:['wallCharge'],ability:'LIVE WIRE',desc:'A reckless ricochet duelist. Wall Charge stores power and speed on every bounce; the next hit releases every charge as a stunning Discharge that partially penetrates parries.',specs:[spec('bolt','Wall Charge cap','5 charges'),spec('trend','Wall Charge speed','+2.5%'),spec('damage','Discharge per charge','1.3 HP'),spec('shield','Parry penetration','25%'),spec('damage','Runaway Comet bonus','+1 HP')]},
  {id:'brick',name:'BRICK',color:'#3759ff',accent:'#aebaff',speed:.83,power:.8518,mass:1.18,behaviors:['armor'],ability:'BREAKWATER',desc:'A walking fortress with three visible Armor Plates. Focused pressure causes Armor Break and opens a brief window before Armor Rebuild restores the shell. Plates provide extra protection from projectiles, echoes, and Overload.',specs:[spec('shield','Plate reduction','26%'),spec('shield','Projectile reduction','32%'),spec('stack','Armor Plates','3'),spec('clock','Armor Rebuild','3 seconds')]},
  {id:'mint',name:'MINT',color:'#20c997',accent:'#abf1dd',speed:1.12,power:1.0045,mass:.9,behaviors:['regeneration'],ability:'SECOND WIND',desc:'A slippery reset specialist. Avoiding damage activates Second Wind; taking another hit immediately stops the healing and restarts its delay.',specs:[spec('clock','Second Wind delay','2 seconds'),spec('plus','Second Wind healing','4.2 HP/s'),spec('impact','Taking damage','Resets Second Wind')]},
  {id:'goldie',name:'GOLDIE',color:'#f6b817',accent:'#ffe49b',speed:.96,power:.9447,mass:1.05,behaviors:['compoundPower'],ability:'JACKPOT',desc:'A combo investor that gains a Coin after each hit. Coins compound Goldie’s power until the fifth triggers Jackpot and cashes out the whole stack.',specs:[spec('trend','Power per Coin','+5%'),spec('stack','Jackpot trigger','5 Coins'),spec('damage','Jackpot bonus','12 HP')]},
  {id:'void',name:'VOID',color:'#191919',accent:'#a4a4a4',speed:1.02,power:.8929,mass:1,behaviors:['siphon'],ability:'THE HUNGER',desc:'A predatory drain-tank whose Siphon heals from damage dealt. Below half health, Feast doubles that healing and starts pulling Void back from the brink.',specs:[spec('drop','Siphon healing','18% of damage'),spec('heart','Feast below 50 HP','36% of damage')]},
  {id:'bubble',name:'BUBBLE',color:'#ef6dca',accent:'#ffc4ef',speed:1.16,power:.9377,mass:.86,behaviors:['bubbleShield'],ability:'POP SCREEN',desc:'A fragile escape artist wrapped in a renewable shield. Shield Pop completely blanks one hit and violently rejects the attacker, then must recharge.',specs:[spec('shield','Shield Pop block','100% damage'),spec('launch','Shield Pop recoil','135% return speed'),spec('clock','Shield recharge','4 seconds')]},
  {id:'moss',name:'MOSS',color:'#658c3a',accent:'#c2dd9e',speed:.88,power:.958,mass:1.12,behaviors:['thorns'],ability:'BRAMBLEHEART',desc:'A spiteful counter-tank whose Thorns return damage and charge Bramble Root on direct hits. Heavy attackers resist a small portion of the return. Once full, Bramble Root pins the attacker in place.',specs:[spec('thorns','Thorns return','28.5–30%'),spec('gauge','Bramble Root charge','18 damage'),spec('clock','Bramble Root','0.5 seconds'),spec('heart','Healing suppression','25%')]},
  {id:'glitch',name:'GLITCH',color:'#9c52ff',accent:'#d9bcff',speed:1.05,power:1.0886,mass:.96,behaviors:['blink'],ability:'BACKDOOR',desc:'A tempo-breaking assassin. Backdoor periodically teleports Glitch behind its target; landing a hit during the brief opening triggers a bonus-damage Desync.',specs:[spec('shuffle','Backdoor interval','3.5 seconds'),spec('clock','Desync window','1 second'),spec('damage','Desync bonus','12 HP')]},
  {id:'frost',name:'FROST',color:'#7bdff2',accent:'#d8f7ff',speed:.91,power:1.0896,mass:1.04,behaviors:['coldSnap'],ability:'SHATTERPOINT',desc:'A setup-and-payoff controller. A heavy direct hit triggers Freeze; connecting again before it ends triggers Ice Shatter for brutal bonus damage.',specs:[spec('impact','Freeze trigger','Heavy direct hit'),spec('snow','Freeze duration','1.5 seconds'),spec('damage','Ice Shatter bonus','16 HP')]},
  {id:'ember',name:'EMBER',color:'#ff6b1a',accent:'#ffc49c',speed:1.01,power:.9617,mass:.97,behaviors:['afterburn'],ability:'FLASHPOINT',desc:'A relentless ignition fighter. Hits build Burn stacks; striking at maximum Burn consumes the flames and triggers an immediate Ignite explosion.',specs:[spec('flame','Maximum Burn','2 stacks'),spec('clock','Burn duration','2 seconds'),spec('damage','Ignite bonus','10 HP')]},
  {id:'echo',name:'ECHO',color:'#00a6a6',accent:'#9ce3df',speed:1.04,power:.8348,mass:.94,behaviors:['echo'],ability:'AFTERIMAGE',desc:'A delayed-damage duelist. Every impact triggers Reverb, scheduling a First Echo and Second Echo that can finish the opponent moments later.',specs:[spec('echo','First Echo','35% at 0.23s'),spec('echo','Second Echo','30% at 0.53s')]},
  {id:'rook',name:'ROOK',color:'#c9c3b9',accent:'#ffffff',speed:.82,power:.7824,mass:1.2,behaviors:['thirdHitBlock'],ability:'CASTLE WALL',desc:'A methodical counter-defender. Two hits test the gates; the third triggers Parry, completely blocking the blow and briefly stunning the aggressor.',specs:[spec('shield','Parry trigger','Every 3rd hit'),spec('block','Parry block','100% damage'),spec('clock','Parry stun','0.17 seconds')]},
  {id:'comet',name:'COMET',color:'#ff477e',accent:'#ffc2d4',speed:1.2,power:1.0886,mass:.82,behaviors:['continuousAcceleration'],ability:'TERMINAL VELOCITY',desc:'A glass-cannon projectile that accelerates while it has room to fly. Speed becomes bonus impact damage and can shatter armor, but every successful ram burns away momentum.',specs:[spec('trend','Speed gain','~6%/second'),spec('damage','High-speed bonus','Up to 12 HP'),spec('shield','At high speed','Breaks all armor'),spec('impact','Speed after hit','86% retained')]},
  {id:'static',name:'STATIC',color:'#e5ff00',accent:'#ffffff',speed:1,power:.9778,mass:.95,behaviors:['fourthStrike'],ability:'OVERLOAD',desc:'A rhythmic brawler with an obvious countdown. Three sparks warn the opponent before the fourth hit triggers Overload and briefly locks them up.',specs:[spec('zap','Overload trigger','Every 4th hit'),spec('damage','Overload bonus','13 HP'),spec('clock','Overload stun','0.3 seconds')]},
  {id:'anchor',name:'ANCHOR',color:'#536878',accent:'#b9c8d2',speed:.72,power:.8482,mass:1.34,behaviors:['woundedPower'],ability:'LAST STAND',desc:'A slow raid boss. Last Stand steadily increases Anchor’s damage and mass as health disappears, making its final moments the most dangerous.',specs:[spec('heart','Last Stand scaling','Missing HP'),spec('damage','Near-zero HP damage','+111%'),spec('weight','Near-zero HP mass','+80%')]},
  {id:'orbit',name:'ORBIT',color:'#6c4cff',accent:'#c9bdff',speed:.96,power:.9684,mass:.98,behaviors:['orbitalSatellites'],ability:'TWIN MOONS',desc:'A moving area-control puzzle. Two physical satellites sweep around Orbit, clipping anyone who approaches on the wrong beat.',specs:[spec('orbit','Satellites','2'),spec('rotate','Satellite spin','1.6 seconds/spin'),spec('damage','Contact damage','5 HP'),spec('clock','Hit cooldown','0.4 seconds')]},
  {id:'saber',name:'SABER',color:'#d93636',accent:'#ffb0a8',speed:.92,power:.8655,mass:1.02,behaviors:['bladeTempo'],weapon:{type:'sword',length:88,width:14,angularSpeed:2.7,damage:21,cooldown:22,knockback:35,reversesOnContact:true},ability:'BLADEDANCE',desc:'A precision executioner whose body barely hurts. A clean Blade Hit deals critical damage and triggers Riposte, reversing the blade and making it spin faster.',specs:[spec('sword','Blade Hit damage','16.1 HP'),spec('damage','Body Hit damage','22% of standard'),spec('rotate','Starting blade spin','2.3 seconds/spin'),spec('trend','Riposte speed','+9%'),spec('rotate','Riposte direction','Reverses spin')]},
  {id:'slugger',name:'SLUGGER',color:'#c47b38',accent:'#f1c590',speed:.88,power:.9283,mass:1.08,behaviors:['slugger'],weapon:{type:'bat',length:80,width:20,angularSpeed:-5.4,damage:4.5,cooldown:25,knockback:245,minimumLaunchSpeed:850,speedMultiplier:1.12},ability:'WALK-OFF',desc:'A positional power hitter. Bat Hit redirects and accelerates the opponent along the swing, arming bonus damage if the launch becomes a Wall Slam.',specs:[spec('bat','Bat Hit damage','3.1 HP'),spec('rotate','Bat spin','1.2 seconds/spin'),spec('trend','Bat Hit speed','At least +12%'),spec('damage','Wall Slam damage','12 HP')]},
  {id:'shotgun',name:'SHOTGUN',color:'#e87924',accent:'#ffd09c',speed:.9,power:1,mass:1.06,behaviors:[],weapon:{type:'shotgun',projectile:true,length:66,width:22,angularSpeed:1.8,fireInterval:72,projectiles:5,spread:.48,projectileSpeed:1080,projectileDamage:4,projectileForce:7,projectileRadius:5,projectileLife:70,fireLabel:'BLAM!'},ability:'FIVE-CARD SPREAD',desc:'A close-range gambler with a rotating scattergun. Five pellets fan out at once, but each disappears on the first wall, hazard, or fighter it touches.',specs:[spec('damage','Damage per pellet','5.1 HP'),spec('stack','Pellets per blast','5'),spec('gauge','Blast spread','27.5° cone'),spec('clock','Fire interval','1.2 seconds'),spec('rotate','Barrel spin','3.5 seconds/spin')]},
  {id:'sniper',name:'SNIPER',color:'#496a81',accent:'#c8e1ed',speed:.78,power:1,mass:1.02,behaviors:[],weapon:{type:'sniper',projectile:true,length:94,width:13,angularSpeed:.82,fireInterval:156,projectiles:1,spread:0,projectileSpeed:1680,projectileDamage:34,projectileForce:16,projectileRadius:3,projectileLife:55,fireLabel:'CRACKSHOT!'},ability:'ONE SHOT, ONE KILL',desc:'A patient long-range executioner. Its narrow barrel rotates slowly and fires one devastating round that vanishes if any piece of terrain intercepts it.',specs:[spec('damage','Round damage','54.5 HP'),spec('clock','Fire interval','2.6 seconds'),spec('rotate','Barrel spin','7.7 seconds/spin')]},
  {id:'lance',name:'LANCE',color:'#feed9a',accent:'#fff8d4',speed:.86,power:1,mass:1.06,behaviors:['joust'],weapon:{type:'lance',length:104,width:11,angularSpeed:1.35,damage:.8,cooldown:18,knockback:55,reversesOnContact:true},ability:'TILT AT FATE',desc:'A feast-or-famine cavalry charge. Lance barely scratches between Jousts, but every hit strengthens the next fast, invulnerable Joust. Brace also softens reckless high-speed rams.',specs:[spec('rotate','Lance spin','4.7 seconds/spin'),spec('clock','Joust interval','2.5 seconds'),spec('shield','During Joust','Invulnerable'),spec('damage','Base Joust damage','12.9 HP'),spec('trend','Joust damage per hit','+1.5 HP'),spec('gauge','Maximum Joust damage','27.9 HP'),spec('damage','Heavy-target bonus','+20%'),spec('shield','Brace reduction','45% at high speed')]},
  {id:'grower',name:'GROWER',color:'#35c94a',accent:'#b8ff82',speed:.9,power:1,mass:.92,behaviors:['growth'],ability:'NO ROOM LEFT',desc:'A living space-control problem. Every wall bounce and body hit makes Grower physically larger, trading a tiny early footprint for relentless late-fight contact pressure—and becoming easier to hit in return.',specs:[spec('trend','Wall growth','+2.3% base size'),spec('impact','Body-hit growth','+4.4% base size'),spec('gauge','Maximum size','155% of base')]},
  {id:'flail',name:'FLAIL',color:'#e2947c',accent:'#ffd5c9',speed:.86,power:1,mass:1.04,behaviors:['wildFlail'],ability:'LOOSE CANNON',desc:'A chaotic scaler built around a separate swinging hurtbox. Each difficult Flail Hit partially bypasses guards and makes the wandering chained head larger and more damaging.',specs:[spec('rotate','Base flail spin','0.73 seconds/spin'),spec('damage','Base Flail Hit','8.5 HP'),spec('trend','Damage per Flail Hit','+1 HP'),spec('gauge','Maximum flail damage','26.8 HP'),spec('trend','Flail-head growth','Up to 2× size'),spec('shield','Guard penetration','50%')]},
  {id:'polar',name:'POLAR',color:'#3366d6',accent:'#9beeff',speed:.96,power:1,mass:1,behaviors:['polarityDrive'],ability:'FIELD REVERSAL',desc:'A rule-breaking position controller. Every direct hit flips its field between attraction and violent repulsion. The field cushions Comet rams, but draws projectiles and loose ability objects dangerously inward.',specs:[spec('magnet','Starting field','Attract'),spec('shuffle','Field reversal','Each direct hit'),spec('shield','Comet ram reduction','10%'),spec('damage','Ability weakness','+10% damage'),spec('damage','Projectile weakness','+40% damage')]},
  {id:'mothership',name:'MOTHERSHIP',color:'#5b3c88',accent:'#c8ff65',speed:.8,power:1,mass:1.1,behaviors:['droneCarrier'],ability:'SCRAMBLE THE SWARM',desc:'A patient carrier that launches up to four homing Seekers. Fast fighters can juke their limited steering, but suffer a harder Seeker Hit if caught. Popping a shield triggers Shield Jam and delays its return.',specs:[spec('clock','Seeker interval','1.53 seconds'),spec('stack','Seeker limit','4 active'),spec('clock','Seeker arming','0.3 seconds'),spec('damage','Seeker Hit damage','4.3–10.6 HP'),spec('shield','Shield penetration','180%'),spec('shield','Melee reduction','15%'),spec('clock','Shield Jam recharge','6 seconds')]},
  {id:'spider',name:'SPIDER',color:'#e2383f',secondaryColor:'#2758c7',accent:'#ffffff',speed:1.02,power:1,mass:.84,radiusScale:.67,behaviors:['webSlinger'],ability:'THWIPLINE',desc:'A tiny aerial trickster with three grapple moves. Grapple Swing accelerates Spider into a heavy Swing Strike. Hitting geometry triggers Perch before a leap, while catching a fighter triggers Web Pull and whips the stopped target inward using its own momentum.',specs:[spec('clock','Grapple interval','0.9–1.8 seconds'),spec('clock','Grapple Swing','1.6 seconds'),spec('damage','Swing Strike bonus','18–36 HP'),spec('clock','Perch duration','1 second'),spec('damage','Web Pull bonus','Up to 20 HP')]},
  {id:'claymore',name:'CLAYMORE',color:'#596b3d',accent:'#ffb14a',speed:.88,power:1,mass:1.08,behaviors:['ordnanceLayer','explosiveResistance'],ability:'DANGER CLOSE',desc:'A demolition tactician that leaves armed Mines in its wake. Mine Blast violently launches whoever finds one, although Claymore resists most of the damage. Grenades burst against fighters or terrain into twelve pieces of Shrapnel.',specs:[spec('clock','Mine interval','3.7–4.7 seconds'),spec('stack','Mine limit','5 active'),spec('damage','Mine Blast damage','34.2 HP'),spec('shield','Blast resistance','65% reduction'),spec('clock','Grenade interval','3.5–4.5 seconds'),spec('stack','Grenade Shrapnel','12 pieces'),spec('damage','Shrapnel damage','3.8 HP each')]},
];

// Balance coefficients are kept separate from kit identity so mechanical tuning
// never obscures the readable fantasy definitions above.
const powerTuning:Record<string,number>={volt:.768,brick:.7,mint:.9083,goldie:1.0686,void:.7613,bubble:1.1287,moss:.8565,glitch:.9484,frost:.78,ember:.788,echo:.7947,rook:.601,comet:1.4159,static:.9283,anchor:.8014,orbit:1.0686,saber:.768,slugger:.6945,shotgun:1.2823,sniper:1.603,lance:1.15,grower:1.1488,flail:1.22,polar:1.32,mothership:.5,spider:.95,claymore:.9};
const bodyDamageTuning:Record<string,number>={volt:.7,brick:.95,mint:.75,goldie:.55,void:.8,bubble:.5,moss:.65,glitch:.6,frost:.55,ember:.65,echo:.6,rook:.8,comet:.5,static:.6,anchor:.65,orbit:.45,saber:.22,slugger:.35,shotgun:.35,sniper:.25,lance:.1,grower:.68,flail:.14,polar:.58,mothership:.625,spider:.62,claymore:.38};
const bodyMaterials:Record<string,Material>={volt:'plastic',brick:'stone',mint:'rubber',goldie:'metal',void:'energy',bubble:'rubber',moss:'wood',glitch:'energy',frost:'glass',ember:'ceramic',echo:'glass',rook:'metal',comet:'glass',static:'energy',anchor:'metal',orbit:'metal',saber:'plastic',slugger:'plastic',shotgun:'plastic',sniper:'plastic',lance:'wood',grower:'rubber',flail:'metal',polar:'energy',mothership:'metal',spider:'rubber',claymore:'metal'};
const weaponMaterials:Record<string,Material>={sword:'metal',bat:'wood',lance:'metal',shotgun:'metal',sniper:'metal'};
for(const fighter of fighters){
  fighter.power=powerTuning[fighter.id];fighter.bodyDamageScale=bodyDamageTuning[fighter.id];fighter.material=bodyMaterials[fighter.id]??'plastic';
  if(fighter.weapon)fighter.weapon.material=weaponMaterials[fighter.weapon.type]??'plastic';
}

export function getFighter(id:string):Fighter|undefined{return fighters.find(fighter=>fighter.id===id);}
