export type SoundSource={
  localUrl:string;
  /** Source-level gain from 0 (silent) to 1 (full recorded level). */
  volume:number;
  sourcePage:string;
  dataMp3Url:string;
  author:string;
  license:'CC0';
  sourceFile?:string;
};

// Edit `volume` here to compensate for a recording that is naturally louder
// or quieter than the rest of the library. Cue-specific mixing lives in
// sound-map.ts; both values are multiplied by the player's master volume.
export const soundSources={
  bodyContact:{
    localUrl:'/audio/body-contact.mp3',
    volume:1,
    sourcePage:'https://opengameart.org/content/click-sounds6',
    dataMp3Url:'https://opengameart.org/sites/default/files/click_sound_1.mp3',
    author:'pauliuw',
    license:'CC0',
    sourceFile:'click_sound_2.mp3',
  },
  metalImpact:{
    localUrl:'/audio/metal-impact.mp3',
    volume:1,
    sourcePage:'https://opengameart.org/content/metal-impact-sounds',
    dataMp3Url:'https://opengameart.org/sites/default/files/audio_preview/clink1.wav.mp3',
    author:'BMacZero',
    license:'CC0',
  },
  mechanicalClank:{
    localUrl:'/audio/mechanical-clank.mp3',
    volume:1,
    sourcePage:'https://opengameart.org/content/mechanical-sounds',
    dataMp3Url:'https://opengameart.org/sites/default/files/audio_preview/clank1.wav.mp3',
    author:'BMacZero',
    license:'CC0',
  },
  bubblePop:{
    localUrl:'/audio/bubble-pop.mp3',
    volume:1,
    sourcePage:'https://opengameart.org/content/pop',
    dataMp3Url:'https://opengameart.org/sites/default/files/pop__0.mp3',
    author:'0f9ran',
    license:'CC0',
  },
  freeze:{
    localUrl:'/audio/freeze-crackle.ogg',
    volume:1,
    sourcePage:'https://opengameart.org/content/100-cc0-sfx-2',
    dataMp3Url:'https://opengameart.org/sites/default/files/audio_preview/sfx100v2_prev.ogg.mp3',
    author:'rubberduck',
    license:'CC0',
    sourceFile:'sfx_100_v2.zip / sfx100v2_glass_04.ogg',
  },
  iceShatter:{
    localUrl:'/audio/ice-shatter.mp3',
    volume:1,
    sourcePage:'https://opengameart.org/content/ice-breakingshattering',
    dataMp3Url:'https://opengameart.org/sites/default/files/audio_preview/LedasLuzta.ogg.mp3',
    author:'IgnasD',
    license:'CC0',
  },
  fire:{
    localUrl:'/audio/fire-ignition.mp3',
    volume:1,
    sourcePage:'https://opengameart.org/content/flare-ignition',
    dataMp3Url:'https://opengameart.org/sites/default/files/ig.mp3',
    author:'qubodup',
    license:'CC0',
    sourceFile:'ignition.flac',
  },
  teleport:{
    localUrl:'/audio/teleport.mp3',
    volume:1,
    sourcePage:'https://opengameart.org/content/teleport',
    dataMp3Url:'https://opengameart.org/sites/default/files/audio_preview/172206_2437358-lq.ogg.mp3',
    author:'fins / diligentcircle',
    license:'CC0',
  },
  healing:{
    localUrl:'/audio/healing.wav',
    volume:1,
    sourcePage:'https://opengameart.org/content/game-sound-effects',
    dataMp3Url:'https://opengameart.org/sites/default/files/Explosion.mp3',
    author:'KASTLE Knight',
    license:'CC0',
    sourceFile:'Sounds(ZW).zip / Powerup.wav',
  },
  coin:{
    localUrl:'/audio/goldie-coin.wav',
    volume:1,
    sourcePage:'https://opengameart.org/content/game-sound-effects',
    dataMp3Url:'https://opengameart.org/sites/default/files/Explosion.mp3',
    author:'KASTLE Knight',
    license:'CC0',
    sourceFile:'Sounds(ZW).zip / Coin.wav',
  },
  burstFire:{
    localUrl:'/audio/burst-fire.mp3',
    volume:1,
    sourcePage:'https://opengameart.org/content/laser-weapon-burst-fire',
    dataMp3Url:'https://opengameart.org/sites/default/files/burst%20fire.mp3',
    author:'celestialghost8',
    license:'CC0',
  },
  shotgunFire:{
    localUrl:'/audio/shotgun-fire.mp3',
    volume:1,
    sourcePage:'https://opengameart.org/content/gunshot-sounds',
    dataMp3Url:'https://opengameart.org/sites/default/files/guns.mp3',
    author:'Tabasco',
    license:'CC0',
    sourceFile:'sounds.zip / sounds/shotty.wav',
  },
  laserFire:{
    localUrl:'/audio/laser-fire.mp3',
    volume:1,
    sourcePage:'https://opengameart.org/node/40732',
    dataMp3Url:'https://opengameart.org/sites/default/files/tir.mp3',
    author:'farfadet46',
    license:'CC0',
  },
  completion:{
    localUrl:'/audio/completion.wav',
    volume:1,
    sourcePage:'https://opengameart.org/content/game-sound-effects',
    dataMp3Url:'https://opengameart.org/sites/default/files/Explosion.mp3',
    author:'KASTLE Knight',
    license:'CC0',
    sourceFile:'Sounds(ZW).zip / Powerup.wav',
  },
  plasticClack:{
    localUrl:'/audio/plastic-clack.mp3',
    volume:1,
    sourcePage:'https://opengameart.org/content/click-sounds6',
    dataMp3Url:'https://opengameart.org/sites/default/files/click_sound_1.mp3',
    author:'pauliuw',
    license:'CC0',
    sourceFile:'click_sound_1.mp3',
  },
  arenaTap:{
    localUrl:'/audio/arena-tap.wav',
    volume:1,
    sourcePage:'https://opengameart.org/content/game-sound-effects',
    dataMp3Url:'https://opengameart.org/sites/default/files/Explosion.mp3',
    author:'KASTLE Knight',
    license:'CC0',
    sourceFile:'Sounds(ZW).zip / Hit.wav',
  },
  rubberBoing:{
    localUrl:'/audio/rubber-pop.ogg',
    volume:1,
    sourcePage:'https://opengameart.org/content/pop-effect-sounds',
    dataMp3Url:'https://opengameart.org/sites/default/files/audio_preview/pop_preview.ogg.mp3',
    author:'Bart Kelsey',
    license:'CC0',
    sourceFile:'p_1.ogg',
  },
  pinballBumper:{
    localUrl:'/audio/pinball-bumper.mp3',
    volume:1,
    sourcePage:'https://opengameart.org/content/boings',
    dataMp3Url:'https://opengameart.org/sites/default/files/boings_preview.mp3',
    author:'Independent.nu',
    license:'CC0',
    sourceFile:'bing_02.mp3',
  },
  metalTap:{
    localUrl:'/audio/metal-tap.ogg',
    volume:1,
    sourcePage:'https://opengameart.org/content/100-cc0-sfx-2',
    dataMp3Url:'https://opengameart.org/sites/default/files/audio_preview/sfx100v2_prev.ogg.mp3',
    author:'rubberduck',
    license:'CC0',
    sourceFile:'sfx_100_v2.zip / sfx100v2_metal_03.ogg',
  },
  woodKnock:{
    localUrl:'/audio/wood-knock.ogg',
    volume:1,
    sourcePage:'https://opengameart.org/content/75-cc0-breaking-falling-hit-sfx',
    dataMp3Url:'https://opengameart.org/sites/default/files/audio_preview/bfh1_prev.ogg.mp3',
    author:'rubberduck',
    license:'CC0',
    sourceFile:'sfx_breaking_and_falling.zip / bfh1_wood_hit_01.ogg',
  },
  stoneKnock:{
    localUrl:'/audio/stone-knock.ogg',
    volume:1,
    sourcePage:'https://opengameart.org/content/75-cc0-breaking-falling-hit-sfx',
    dataMp3Url:'https://opengameart.org/sites/default/files/audio_preview/bfh1_prev.ogg.mp3',
    author:'rubberduck',
    license:'CC0',
    sourceFile:'sfx_breaking_and_falling.zip / bfh1_rock_hit_01.ogg',
  },
  glassTick:{
    localUrl:'/audio/glass-tick.ogg',
    volume:1,
    sourcePage:'https://opengameart.org/content/75-cc0-breaking-falling-hit-sfx',
    dataMp3Url:'https://opengameart.org/sites/default/files/audio_preview/bfh1_prev.ogg.mp3',
    author:'rubberduck',
    license:'CC0',
    sourceFile:'sfx_breaking_and_falling.zip / bfh1_glass_hit_01.ogg',
  },
  softThud:{
    localUrl:'/audio/soft-hit.ogg',
    volume:1,
    sourcePage:'https://opengameart.org/content/100-cc0-sfx-2',
    dataMp3Url:'https://opengameart.org/sites/default/files/audio_preview/sfx100v2_prev.ogg.mp3',
    author:'rubberduck',
    license:'CC0',
    sourceFile:'sfx_100_v2.zip / sfx100v2_hit_03.ogg',
  },
  flailRattle:{
    localUrl:'/audio/flail-rattle.wav',
    volume:.9,
    sourcePage:'https://opengameart.org/content/mechanical-sounds',
    dataMp3Url:'https://opengameart.org/sites/default/files/audio_preview/clank1.wav.mp3',
    author:'BMacZero',
    license:'CC0',
    sourceFile:'rattle1.wav',
  },
  lanceWhoosh:{
    localUrl:'/audio/lance-whoosh.wav',
    volume:.9,
    sourcePage:'https://opengameart.org/content/swishes-sound-pack',
    dataMp3Url:'https://opengameart.org/sites/default/files/swishprev.mp3',
    author:'artisticdude',
    license:'CC0',
    sourceFile:'swishes.zip / swish-7.wav',
  },
  lanceHit:{
    localUrl:'/audio/lance-hit.wav',
    volume:.8,
    sourcePage:'https://opengameart.org/content/swishes-sound-pack',
    dataMp3Url:'https://opengameart.org/sites/default/files/swishprev.mp3',
    author:'artisticdude',
    license:'CC0',
    sourceFile:'swishes.zip / swish-13.wav',
  },
} as const satisfies Record<string,SoundSource>;
