export type Side = 'left' | 'right';
export type Winner = Side | 'draw';
export type RandomSource = () => number;
export type Material = 'plastic'|'metal'|'stone'|'wood'|'rubber'|'glass'|'energy'|'ceramic';
export type DamageType = 'physical'|'burn'|'poison'|'acid'|'ice'|'electric'|'explosive'|'echo'|'time'|'hazard'|'fatigue';
export type HealthDamageReceipt = { sequence:number; from:number; to:number; amount:number; type:DamageType };
export type HealthHealingReceipt = { sequence:number; from:number; to:number; amount:number };
export type SoundCue = 'maestroTap'|'maestroCrescendo'|'bassDrop'|'oracleVision'|'fateStrike'|'fateEvaded'|'stringSnap'|'unbound'|'restring'|'spotlight'|'laserSweep'|'laserHit'|'dataBlade'|'bladeAnchor'|'phaseBlink'|'phaseCut'|'intercept'|'retaliation'|'enforcerReturn'|'meditate'|'serenityWard'|'meditationBreak'|'palmStrike'|'ascend'|'clinch'|'ringToss'|'phantomSpawn'|'phantomStrike'|'flaskThrow'|'flaskBreak'|'acidSizzle'|'catalystBurst'|'roninFocus'|'roninCut'|'roninCounter'|'portalOpen'|'portalTravel'|'portalCollapse'|'pylonPlace'|'arcZap'|'shellBreak'|'coreBurst'|'crescentCast'|'crescentRecall'|'crescentHit'|'crescentCatch'|'rocketWindup'|'rocketPunch'|'rocketBurst'|'timeMark'|'timeRewind'|'bodyContact'|'wallContact'|'impactLight'|'impactHeavy'|'materialPlastic'|'materialWall'|'materialRubber'|'materialWood'|'materialStone'|'materialGlass'|'materialSoft'|'materialMetal'|'materialEnergy'|'armorBlock'|'armorBreak'|'bubblePop'|'freeze'|'iceShatter'|'fire'|'poison'|'teleport'|'heal'|'coin'|'jackpot'|'electric'|'shotgun'|'sniper'|'sword'|'bat'|'lanceCharge'|'lanceHit'|'grow'|'flail'|'magnetPull'|'magnetPush'|'droneLaunch'|'droneHit'|'webShot'|'webSwing'|'webImpact'|'webPerch'|'mineDeploy'|'explosion'|'grenade'|'shrapnel'|'root'|'echo'|'siphon'|'whoosh'|'rumble'|'pinball'|'success'|'failure';
export type SoundCueOptions = {volume?:number;rate?:number};
export type Point = { x: number; y: number };
export type Bounds = { left: number; right: number; top: number; bottom: number };

export type FighterSpec = { icon: string; label: string; value: string };

type WeaponBase = {
  type: 'sword' | 'bat' | 'lance' | 'shotgun' | 'sniper';
  length: number;
  width: number;
  angularSpeed: number;
  material?: Material;
};

export type MeleeWeapon = WeaponBase & {
  type: 'sword' | 'bat' | 'lance';
  projectile?: false;
  damage: number;
  cooldown: number;
  knockback: number;
  reversesOnContact?: boolean;
  minimumLaunchSpeed?: number;
  speedMultiplier?: number;
};

export type RangedWeapon = WeaponBase & {
  type: 'shotgun' | 'sniper';
  projectile: true;
  fireInterval: number;
  projectiles: number;
  spread: number;
  projectileSpeed: number;
  projectileDamage: number;
  projectileForce: number;
  projectileRadius: number;
  projectileLife: number;
  fireLabel: string;
};

export type Weapon = MeleeWeapon | RangedWeapon;

export type Fighter = {
  id: string;
  name: string;
  color: string;
  secondaryColor?: string;
  accent: string;
  shineColor?: string;
  material?: Material;
  speed: number;
  power: number;
  mass: number;
  radiusScale?: number;
  behaviors: string[];
  ability: string;
  desc: string;
  specs: FighterSpec[];
  bodyDamageScale?: number;
  poisonDamageScale?: number;
  weapon?: Weapon;
};

export type HazardType = 'pillar' | 'spikes' | 'medbay' | 'pinball';
export type Hazard = Point & { id: string; type: HazardType; r: number; value: number };

export type WallCrash = { frames: number; damage: number };
export type Portal = Point&{nx:number;ny:number;color:string;wall:number};
export type CircuitNode = Point&{nx:number;ny:number;born:number};
export type PhantomEcho = Point&{path:Point[];progress:number;hit:boolean};
export type FlaskKind = 'acid'|'tonic'|'catalyst';
export type AlchemyFlask = Point&{vx:number;vy:number;kind:FlaskKind;rotation:number;dead:boolean};
export type AlchemyPool = Point&{kind:'acid'|'tonic';radius:number;frames:number};
export type RoninState = {phase:'focus'|'dash'|'recovery';frames:number;angle:number;hit:boolean;counter:boolean;final:boolean;startedTick:number};
export type PalmRelease = {frames:number;dx:number;dy:number};
export type LuchaState = {frames:number;cx:number;cy:number;angle:number;direction:1|-1};
export type NeonState = {phase:'charge'|'sweep';frames:number;angle:number;direction:1|-1;hit:boolean};
export type DataBlade = Point&{vx:number;vy:number;phase:'flying'|'anchored';frames:number;nx:number;ny:number;rotation:number};
export type OracleVision = Point&{frames:number};

export type Ball = Point & {
  f: Fighter;
  side: Side;
  vx: number;
  vy: number;
  tickStartX?: number;
  tickStartY?: number;
  radius: number;
  angle: number;
  angularVelocity: number;
  hp: number;
  mass?: number;
  cooldown: number;
  hazardCooldowns: Record<string, number>;
  weaponCooldown: number;
  weaponWorldCooldown: number;
  fireCooldown: number;
  stunned: number;
  frozen: boolean;
  flash: number;
  powerScale: number;
  hits: number;
  incoming: number;
  burn: number;
  burnStacks: number;
  poisonStacks: number;
  poisonTick: number;
  healthDamageReceipts?: HealthDamageReceipt[];
  healthDamageSequence?: number;
  healthHealingReceipts?: HealthHealingReceipt[];
  healthHealingSequence?: number;
  wallBoost: number;
  wallCrash: WallCrash | null;
  visualStates: Record<string,number>;
  crescent?: {x:number;y:number;vx:number;vy:number;age:number;returning:boolean;outHit:boolean;backHit:boolean};
  crescentCooldown?: number;
  rocket?: {phase:'windup'|'dash'|'recovery';frames:number;angle:number;hit:boolean};
  rocketCooldown?: number;
  timeAnchor?: {x:number;y:number;vx:number;vy:number;frames:number;damage:number};
  timeCooldown?: number;
  portals?: Portal[];
  portalPlacementCooldown?: number;
  portalNextIndex?: number;
  portalTransfers?: number;
  portalCooldown?: number;
  portalStrikeFrames?: number;
  circuitNodes?: CircuitNode[];
  circuitVersion?: number;
  circuitOvercharge?: number;
  circuitCooldowns?: Record<string,number>;
  nestPhase?: 1|2|3;
  nestBaseRadius?: number;
  nestWeaponCooldown?: number;
  coreCountdown?: number;
  formColor?: string;
  phantomHistory?: Point[];
  phantomEcho?: PhantomEcho;
  phantomCooldown?: number;
  phantomMisdirect?: boolean;
  alchemyFlasks?: AlchemyFlask[];
  alchemyPools?: AlchemyPool[];
  alchemyCooldown?: number;
  alchemyIndex?: number;
  ronin?: RoninState;
  roninCooldown?: number;
  roninResolve?: number;
  stillpointCooldown?: number;
  meditationFrames?: number;
  meditationVx?: number;
  meditationVy?: number;
  meditationSetbacks?: number;
  palmReady?: boolean;
  stillpointSpent?: boolean;
  serenityWard?: boolean;
  palmRelease?: PalmRelease;
  ascended?: boolean;
  ascendantBaseRadius?: number;
  ascensionFrames?: number;
  ascensionLaunchVx?: number;
  ascensionLaunchVy?: number;
  invulnerable?: boolean;
  luchaCooldown?: number;
  luchaState?: LuchaState;
  luchaCaptured?: boolean;
  neonCooldown?: number;
  neonState?: NeonState;
  neonStoredVx?: number;
  neonStoredVy?: number;
  dataBlade?: DataBlade;
  dataBladeCooldown?: number;
  phaseCutFrames?: number;
  phaseCutReady?: boolean;
  enforcerCooldown?: number;
  enforcerAngle?: number;
  maestroBeat?: number;
  oracleCooldown?: number;
  oracleVision?: OracleVision;
  puppetStrings?: number;
  stringSnapCooldown?: number;
  unboundFrames?: number;
  puppetBoundSpeed?: number;
  voltCharge?: number;
  armorPlates?: number;
  armorRepair?: number;
  mintRest?: number;
  goldStacks?: number;
  bubbleShield?: boolean;
  bubbleRecharge?: number;
  sporeMeter?: number;
  phaseFrames?: number;
  frostFrozenUntil?: number;
  orbitCooldown?: number;
  joustCooldown?: number;
  joustFrames?: number;
  joustDamage?: number;
  growthBaseRadius?: number;
  flailAngle?: number;
  flailSpeed?: number;
  flailDamage?: number;
  flailRadius?: number;
  flailReach?: number;
  flailCooldown?: number;
  polarity?: 1|-1;
  carrierCooldown?: number;
  mineCooldown?: number;
  grenadeCooldown?: number;
  grappleCooldown?: number;
  grappleMode?: 'casting'|'swinging'|'pulling'|'perched';
  grappleTarget?: 'fighter'|'geometry';
  grappleX?: number;
  grappleY?: number;
  grappleLength?: number;
  grappleFrames?: number;
  grappleCastFrames?: number;
  grappleCastDuration?: number;
  grappleOriginX?: number;
  grappleOriginY?: number;
  grappleDirectionX?: number;
  grappleDirectionY?: number;
  grappleTravel?: number;
  grappleRange?: number;
  grappleDirection?: 1|-1;
  perchNormalX?: number;
  perchNormalY?: number;
};

export type CombatEvent = {
  force: number;
  damage: number;
  dt?: number;
  weapon?: boolean;
  projectile?: boolean;
  echo?: boolean;
  ability?: boolean;
  unblockable?: boolean;
  parryPenetration?: number;
  armorPenetration?: number;
  armorDamage?: number;
  shieldPenetration?: number;
  rocketGuard?: boolean;
  portalStrike?: boolean;
  phantomMisdirect?: boolean;
  roninCut?: boolean;
  roninCounter?: boolean;
  palmStrike?: boolean;
  meditationBreak?: boolean;
  serenityReflect?: boolean;
  ascensionReject?: boolean;
  luchaClinch?: boolean;
  phaseCut?: boolean;
  capoIntercept?: boolean;
  maestroBeat?: number;
  unboundStrike?: boolean;
  healingScale?: number;
  voltRelease?: number;
  bubblePop?: boolean;
  jackpot?: boolean;
  phaseStrike?: boolean;
  iceShatter?: boolean;
  ignite?: boolean;
  blockedDamage?: number;
  rookBlock?: boolean;
  staticBurst?: boolean;
  attackerSpeed?: number;
  targetSpeed?: number;
  swingStrike?: boolean;
  webPull?: boolean;
  geometry?: {x:number;y:number;nx:number;ny:number;type:'wall'|'hazard'};
  explosive?: boolean;
  damageType?: DamageType;
};

export type Echo = { attacker: Ball; victim: Ball; frames: number; damage: number };
export type ProjectileType = RangedWeapon['type']|'heatseeker'|'grenade'|'shrapnel'|'timeShard'|'shellShard';
export type Projectile = Point & {
  shooter: Ball;
  side: Side;
  previousX: number;
  previousY: number;
  vx: number;
  vy: number;
  radius: number;
  damage: number;
  force: number;
  life: number;
  color: string;
  type: ProjectileType;
  dead: boolean;
  homingAcceleration?: number;
  maxSpeed?: number;
  turnRate?: number;
  armingFrames?: number;
  rotation?: number;
  spin?: number;
  volleyId?: string;
  portalCooldown?: number;
  chargedNetworks?: string[];
  electricCharge?: boolean;
  coreBurst?: boolean;
};

export type Mine = Point & {
  id:string;
  owner:Ball;
  side:Side;
  radius:number;
  damage:number;
  launchSpeed:number;
  armingFrames:number;
  dead:boolean;
};

export type Particle = Point & {
  vx: number;
  vy: number;
  life: number;
  color: string;
  gravity?: number;
  rotation?: number;
  spin?: number;
  stroke?: string|null;
  kind?: string;
  size?: number;
};

export type Exchange = {
  tick: number;
  source: string;
  before: Record<Side, number>;
  after: Record<Side, number>;
  damageTaken: Record<Side, number>;
};

export type Simulation = {
  balls: Ball[];
  projectiles: Projectile[];
  mines: Mine[];
  rng: RandomSource;
  ticks: number;
  hitStop: number;
  echoes: Echo[];
  hazards: Hazard[];
  lastExchange: Exchange | null;
  width: number;
  height: number;
  particles: Particle[];
  impactPopups: ImpactPopup[];
  visualRng: RandomSource;
  finished: boolean;
  events: Record<string, number>;
};

export type ImpactPopup = Point & { word: string; born: number; size: number; rotation: number; color: string };
export type Bout = { left: Fighter; right: Fighter; hazards: Hazard[]; seed: number; outcome?: 'win' | 'loss' };

export type Outcome = {
  winner: Winner;
  mutualKo: boolean;
  decidedBy: 'knockout' | 'overkillHp' | 'finalDamage' | 'kineticEnergy' | 'landedHits' | 'deadHeat';
  exchange?: Exchange | null;
  leftHp?: number;
  rightHp?: number;
  hpMargin?: number;
  leftEnergy?: number;
  rightEnergy?: number;
};

export type WeaponHit = {
  attacker: Ball;
  victim: Ball;
  damage: number;
  force: number;
  impulseX: number;
  impulseY: number;
  redirect: { x: number; y: number; minimumSpeed: number; speedMultiplier: number } | null;
  label: string;
};

export type ProjectileHit = { projectile: Projectile; target?: Ball; x: number; y: number; world?: boolean };
export type MineHit = {mine:Mine;target:Ball;x:number;y:number;damage:number;force:number;launchX:number;launchY:number};

export type BalanceSummary = {
  wins:number;losses:number;draws:number;games:number;score:number;winRate:number;drawRate:number;
  averageSeconds:number;averageRemainingHp:number;averageOpponentHp:number;
};
export type BalanceMatch = BalanceSummary&{asLeft:BalanceSummary;asRight:BalanceSummary};
export type BalanceRanking = { id:string;name:string;tier:string;wins:number;losses:number;draws:number;games:number;score:number;asLeft:BalanceSummary;asRight:BalanceSummary };
export type BalanceReport = {
  method:{totalSimulations:number;seedsPerSide:number};
  rankings:BalanceRanking[];
  matrix:Record<string,Record<string,BalanceMatch|null>>;
};

export type ParticleOptions = { count?:number;color?:string;speed?:number;gravity?:number;kind?:string;size?:number;pattern?:'burst'|'spiral';spawnRadius?:number };
export type BehaviorContext = {
  ball: Ball;
  rival: Ball;
  sim: Simulation;
  event: CombatEvent;
  random: RandomSource;
  showImpact: (word:string,origin:Point|Ball)=>void;
  emitParticles: (origin:Point|Ball,options?:ParticleOptions)=>void;
  audioTone: (frequency:number,duration:number,type?:OscillatorType,volume?:number)=>void;
  audioHit: (power:number)=>void;
  playSound: (cue:SoundCue,options?:SoundCueOptions)=>void;
  ctx: CanvasRenderingContext2D;
};

export type BehaviorHook = 'wallHit'|'geometryHit'|'modifyOutgoing'|'dealHit'|'draw'|'tick'|'modifyIncoming'|'takeHit'|'beforeMove'|'beforeOutcome'|'drawFloor'|'drawBack'|'drawFront';
export type Behavior = Partial<Record<BehaviorHook,(context:BehaviorContext)=>void>>;
